name: tfsec
on:
  workflow_call:
    inputs:
      sarif_file:
        description: 'Path to the SARIF file relative to the repository root'
        required: true

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@v0.1.0
        with:
          sarif_file: ${{ inputs.sarif_file }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ inputs.sarif_file }}

      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.Github_TOKEN }}

# Define a workflow that uses the template
# Example usage: 
#- name: Trigger tfsec workflow
#  uses: .github/workflows/tfsec-template.yml@main
#  with:
#    sarif_file: path/to/your-sarif-file.sarif            
