name: Release and Rollback

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

  rollback:
    name: Rollback Release
    needs: release
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Release
        uses: author/action-rollback@stable
        with:
          # Using a known release ID
          release_id: ${{ steps.create_release.id }}
          # Using a tag name
          tag: ${{ github.run_number }}
          # If the release does not exist but the tag does, setting this to true will remove the tag.
          #delete_orphan_tag: true
        env: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
