on:
  workflow_call:
    inputs:
      version:
       description: 'Version of Terraform Cleaner'
       required: true
       type: string
       default: '0.0.4'
    secrets:
      GH_PAT:
        required: true

jobs:
  tf-vars-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform Cleaner
        run: |
          VERSION="${{ github.event.inputs.version }}"
          wget https://github.com/sylwit/terraform-cleaner/releases/download/v${{ github.event.inputs.version || '0.0.4' }}/terraform-cleaner_${{ github.event.inputs.version || '0.0.4' }}_linux_amd64.tar.gz
          tar -xvf terraform-cleaner_${{ github.event.inputs.version || '0.0.4' }}_linux_amd64.tar.gz
          
      - name: Run Terraform Cleaner
        id: terraform-cleaner
        run: |
          mv terraform-cleaner /usr/local/bin
          echo "output=$(echo $(terraform-cleaner))" >> $GITHUB_ENV
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          
      - name: Check Cleaner Output
        run: |
         echo "Cleaner Output:"
         echo $output
         
      - name: Get PR number
        id: PR
        run: echo "Pull Request number is ${{ github.event.pull_request.number }}"
       
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: |
            Test with ${{ github.sha }}.
            ```
            ${{ env.output }}
            ```
