on:
  workflow_call:
    inputs:
      version:
       description: 'Version of Terraform Cleaner'
       required: false
       type: string
       default: '0.0.4'
    secrets:
      GH_PAT:
        required: true

jobs:
  tf-vars-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform Cleaner
        run: |
          VERSION="${{ inputs.version || github.event.inputs.version }}"
          wget https://github.com/sylwit/terraform-cleaner/releases/download/v${VERSION}/terraform-cleaner_${VERSION}_linux_amd64.tar.gz
          tar -xvf terraform-cleaner_${VERSION}_linux_amd64.tar.gz
          
      - name: Run Terraform Cleaner
        id: terraform-cleaner
        run: |
          mv terraform-cleaner /usr/local/bin
          echo "output=$(echo $(terraform-cleaner))" >> $GITHUB_ENV
                   
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: |
            Output of Terraform Cleaner: ${{ github.sha }}.
            ```
            ${{ env.output }}
            ```
